{% set version = '0.1.191' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-survivalmodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survivalmodels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survivalmodels/survivalmodels_{{ version }}.tar.gz
  sha256: 0083b0ff1d29c82d70b90e13862cb3a9e6cb0619deb4107d06d4838c95bb8b47

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0.5
  run:
    - r-base
    - r-rcpp >=1.0.5

test:
  commands:
    - $R -e "library('survivalmodels')"           # [not win]
    - "\"%R%\" -e \"library('survivalmodels')\""  # [win]

about:
  home: https://github.com/RaphaelS1/survivalmodels/
  license: MIT
  summary: Implementations of classical and machine learning models for survival analysis, including
    deep neural networks via 'keras' and 'tensorflow'. Each model includes a separated
    fit and predict interface with consistent prediction types for predicting risk or
    survival probabilities. Models are either implemented from 'Python' via 'reticulate'
    <https://CRAN.R-project.org/package=reticulate>, from code in GitHub packages, or
    novel implementations using 'Rcpp' <https://CRAN.R-project.org/package=Rcpp>. Neural
    networks are implemented from the 'Python' package 'pycox' <https://github.com/havakv/pycox>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: survivalmodels
# Title: Models for Survival Analysis
# Version: 0.1.191
# Authors@R: c(person(given = "Raphael", family = "Sonabend", role = c("aut"), comment = c(ORCID = "0000-0001-9225-4654")), person(given = "Yohann", family = "Foucher", role = c("cre"), email = "yohann.foucher@univ-poitiers.fr", comment = c(ORCID = "0000-0003-0330-7457")))
# Description: Implementations of classical and machine learning models for survival analysis, including deep neural networks via 'keras' and 'tensorflow'. Each model includes a separated fit and predict interface with consistent prediction types for predicting risk or survival probabilities. Models are either implemented from 'Python' via 'reticulate' <https://CRAN.R-project.org/package=reticulate>, from code in GitHub packages, or novel implementations using 'Rcpp' <https://CRAN.R-project.org/package=Rcpp>. Neural networks are implemented from the 'Python' package 'pycox' <https://github.com/havakv/pycox>.
# License: MIT + file LICENSE
# URL: https://github.com/RaphaelS1/survivalmodels/
# BugReports: https://github.com/foucher-y/survivalmodels/issues
# Imports: Rcpp (>= 1.0.5)
# Suggests: keras (>= 2.11.0), pseudo, reticulate, survival
# LinkingTo: Rcpp
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2024-03-18 21:10:19 UTC; foucher-y
# Author: Raphael Sonabend [aut] (<https://orcid.org/0000-0001-9225-4654>), Yohann Foucher [cre] (<https://orcid.org/0000-0003-0330-7457>)
# Maintainer: Yohann Foucher <yohann.foucher@univ-poitiers.fr>
# Repository: CRAN
# Date/Publication: 2024-03-19 16:50:03 UTC
